# Generated by Django 3.2.5 on 2021-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210726_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.CharField(choices=[('1', 'Red Ville'), ('2', 'Red Cross'), ('3', 'The Park'), ('4', 'BEACH'), ('5', 'BMW'), ('6', 'Deer'), ('7', 'Kenya Police')], default='Red Ville', max_length=25),
        ),
    ]
